name = "word30210/hangul_luau"
version = "1.0.0"
authors = ["word30210"]
repository = "https://github.com/Word30210/hangul-luau"
license = "MIT"
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**",
    ".luaurc"
]

[target]
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
better_table = { name = "word30210/better_table", version = "^1.0.0" }
frktest = { name = "itsfrank/frktest", version = "^0.0.2" }
